//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheatLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheatLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss.
        /// </summary>
        internal static string abyss {
            get {
                return ResourceManager.GetString("abyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string achievements {
            get {
                return ResourceManager.GetString("achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto pickup.
        /// </summary>
        internal static string auto_f {
            get {
                return ResourceManager.GetString("auto_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto loot.
        /// </summary>
        internal static string auto_pick_up {
            get {
                return ResourceManager.GetString("auto_pick_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically opens chests with other treasures..
        /// </summary>
        internal static string auto_treassure_tootip {
            get {
                return ResourceManager.GetString("auto_treassure_tootip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto treasure.
        /// </summary>
        internal static string auto_treasure {
            get {
                return ResourceManager.GetString("auto_treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera zoom.
        /// </summary>
        internal static string camera_zoom {
            get {
                return ResourceManager.GetString("camera_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay range (ms).
        /// </summary>
        internal static string delay_time__ms_ {
            get {
                return ResourceManager.GetString("delay_time__ms_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enka.
        /// </summary>
        internal static string enka {
            get {
                return ResourceManager.GetString("enka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max zoom.
        /// </summary>
        internal static string max_zoom {
            get {
                return ResourceManager.GetString("max_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable increasing camera zoom..
        /// </summary>
        internal static string max_zoom_tooltip {
            get {
                return ResourceManager.GetString("max_zoom_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto pickup dropped items for you. Works with random delay to simulate human-like behavior..
        /// </summary>
        internal static string pickup_tooltip {
            get {
                return ResourceManager.GetString("pickup_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Tab.
        /// </summary>
        internal static string refresh_tab {
            get {
                return ResourceManager.GetString("refresh_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate human.
        /// </summary>
        internal static string simulate_human {
            get {
                return ResourceManager.GetString("simulate_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom scale: {0}.
        /// </summary>
        internal static string zoom_scale {
            get {
                return ResourceManager.GetString("zoom_scale", resourceCulture);
            }
        }
    }
}
