//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheatLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheatLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss.
        /// </summary>
        public static string Abyss {
            get {
                return ResourceManager.GetString("Abyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string achievements {
            get {
                return ResourceManager.GetString("achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string authorizing {
            get {
                return ResourceManager.GetString("authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto pickup.
        /// </summary>
        public static string auto_loot {
            get {
                return ResourceManager.GetString("auto_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Loot.
        /// </summary>
        public static string auto_loot_header {
            get {
                return ResourceManager.GetString("auto_loot_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pickup loot nearby. Simulates human to avoid possible ban..
        /// </summary>
        public static string auto_loot_help {
            get {
                return ResourceManager.GetString("auto_loot_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto treasure.
        /// </summary>
        public static string auto_treasure {
            get {
                return ResourceManager.GetString("auto_treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically opens chests and other treasures..
        /// </summary>
        public static string auto_treasure_help {
            get {
                return ResourceManager.GetString("auto_treasure_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Zoom.
        /// </summary>
        public static string camera_zoom {
            get {
                return ResourceManager.GetString("camera_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ESP.
        /// </summary>
        public static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual guides to game objects..
        /// </summary>
        public static string enable_esp_help {
            get {
                return ResourceManager.GetString("enable_esp_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public characters.
        /// </summary>
        public static string Enka {
            get {
                return ResourceManager.GetString("Enka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP.
        /// </summary>
        public static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Max Zoom.
        /// </summary>
        public static string increase_max_zoom {
            get {
                return ResourceManager.GetString("increase_max_zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit hoyolab.com....
        /// </summary>
        public static string on_auth_help {
            get {
                return ResourceManager.GetString("on_auth_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking daily sign-up....
        /// </summary>
        public static string on_sign_help {
            get {
                return ResourceManager.GetString("on_sign_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving game info....
        /// </summary>
        public static string on_user_card_help {
            get {
                return ResourceManager.GetString("on_user_card_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
